-- MySQL Script generated by MySQL Workbench
-- Thu Oct 30 09:12:28 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`localidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `localidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departamento_localidade1_idx` (`localidade_id` ASC),
  CONSTRAINT `fk_departamento_localidade1`
    FOREIGN KEY (`localidade_id`)
    REFERENCES `mydb`.`localidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`academico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `departamento_id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_academico_departamento1_idx` (`departamento_id` ASC),
  CONSTRAINT `fk_academico_departamento1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `mydb`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `cartaz` VARCHAR(45) NOT NULL,
  `incio` DATETIME NOT NULL,
  `fim` DATETIME NOT NULL,
  `descricao` TINYTEXT NOT NULL,
  `academico_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_academico1_idx` (`academico_id` ASC),
  CONSTRAINT `fk_evento_academico1`
    FOREIGN KEY (`academico_id`)
    REFERENCES `mydb`.`academico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cronograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cronograma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `evento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cronograma_evento_idx` (`evento_id` ASC),
  CONSTRAINT `fk_cronograma_evento`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apoio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apoio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NULL,
  `evento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_apoio_evento1_idx` (`evento_id` ASC),
  CONSTRAINT `fk_apoio_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `horario` TIME NOT NULL,
  `descricao` TINYTEXT NOT NULL,
  `cronograma_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividade_cronograma1_idx` (`cronograma_id` ASC),
  CONSTRAINT `fk_atividade_cronograma1`
    FOREIGN KEY (`cronograma_id`)
    REFERENCES `mydb`.`cronograma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `academico_id` INT NOT NULL,
  `matricula` VARCHAR(20) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  PRIMARY KEY (`academico_id`),
  CONSTRAINT `fk_aluno_academico1`
    FOREIGN KEY (`academico_id`)
    REFERENCES `mydb`.`academico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `academico_id` INT NOT NULL,
  `siape` INT UNSIGNED NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`academico_id`),
  CONSTRAINT `fk_professor_academico1`
    FOREIGN KEY (`academico_id`)
    REFERENCES `mydb`.`academico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento_has_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento_has_evento` (
  `departamento_id` INT NOT NULL,
  `evento_id` INT NOT NULL,
  PRIMARY KEY (`departamento_id`, `evento_id`),
  INDEX `fk_departamento_has_evento_evento1_idx` (`evento_id` ASC),
  INDEX `fk_departamento_has_evento_departamento1_idx` (`departamento_id` ASC),
  CONSTRAINT `fk_departamento_has_evento_departamento1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `mydb`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departamento_has_evento_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`campus` (
  `nome` VARCHAR(45) NOT NULL,
  `localidade_id` INT NOT NULL,
  `codigo` VARCHAR(5) NOT NULL,
  INDEX `fk_campus_localidade1_idx` (`localidade_id` ASC),
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_campus_localidade1`
    FOREIGN KEY (`localidade_id`)
    REFERENCES `mydb`.`localidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instalacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instalacao` (
  `predio` VARCHAR(45) NOT NULL,
  `localidade_id` INT NOT NULL,
  `campus_codigo` VARCHAR(5) NOT NULL,
  INDEX `fk_instalacao_localidade1_idx` (`localidade_id` ASC),
  INDEX `fk_instalacao_campus1_idx` (`campus_codigo` ASC),
  CONSTRAINT `fk_instalacao_localidade1`
    FOREIGN KEY (`localidade_id`)
    REFERENCES `mydb`.`localidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instalacao_campus1`
    FOREIGN KEY (`campus_codigo`)
    REFERENCES `mydb`.`campus` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento_has_localidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento_has_localidade` (
  `evento_id` INT NOT NULL,
  `localidade_id` INT NOT NULL,
  PRIMARY KEY (`evento_id`, `localidade_id`),
  INDEX `fk_evento_has_localidade_localidade1_idx` (`localidade_id` ASC),
  INDEX `fk_evento_has_localidade_evento1_idx` (`evento_id` ASC),
  CONSTRAINT `fk_evento_has_localidade_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_localidade_localidade1`
    FOREIGN KEY (`localidade_id`)
    REFERENCES `mydb`.`localidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
